### PR TITLE
Expanded name

### PR DESCRIPTION
**Pull request by tjj2017**
In Do_Expression N_Expanded_Name was not being handled which led to many faults including rating an exception due to a failed precondition at arrays.ads line 57.

The gnat front-end replaces all instances of a selected_component by an expanded_name except for those instances which are actually a component selection.

In Do_Expression N_Expanded_Name is treated as an N_Identifier.

### CODE REVIEW

**Comment by tjj2017** [comment]
Updated golden results again.  I don't know what went wrong the first time?

**Comment by xbauch** [comment]
@tjj2017 it seems you have had an old version of `master` when committing this work. I guess the easiest fix would be to `git remote update diffblue --prune` start a new local branch based on `diffblue:master`, cherry-pick the one commit from here, run and update the golden results, and then force-push into this branch.

**Comment by chrisr-diffblue** [comment]
@tjj2017 - I think this just needs rebasing to update the golden results, then we should be able to merge.

**Comment by tjj2017** [comment]
I have been unable to resolve the conflicts remotely and have done it directly via GitHub.

**Comment by xbauch** [comment]
Merged as part of #271.

**Pull request closed without merging**
