### PR TITLE
Enable the generation of ali files for use by the binder

### PR DESCRIPTION
**Pull request by tjj2017**

### CODE REVIEW

**Comment by tjj2017** [comment]
I do not believe this change should have changed the golden results.
The golden results of Stratox on the master branch do not report any GNAT BUG exceptions but there are many in the Stratox.txt file when CI_list_unsupported is run on master. When CI_list_unsupported is run on this branch the Stratox-summary.txt file contains a half printed out of one of these GNAT BUGs.

**Comment by martin-cs** [comment]
Let's have a look at what happens now that https://github.com/diffblue/gnat2goto/pull/275 has been merged.

**Comment by chrisr-diffblue** [comment]
I've just restarted the travis job so that it picks up the changes to list_unsupported.sh in master. This means all the GNAT BUG failures get collected, and as such, it's now showing that the code change in this PR does indeed cause some extra GNAT BUG reports to trigger, so golden results will need updating.

**Comment by martin-cs** [comment]
@tjj2017 I have asked @chrisr-diffblue and team to pick this up and get it merged.

**Comment by chrisr-diffblue** [comment]
The changes in this PR have been incorporated and merged in #276. Closing this PR.

**Comment by martin-cs** [comment]
Merged as #276

**Pull request closed without merging**
