### PR TITLE
Update/cbmc submodule may 2020

### PR DESCRIPTION
**Pull request by martin-cs**

### CODE REVIEW

**Comment by martin-cs** [comment]
This updates to the last working CBMC version.  https://github.com/diffblue/cbmc/pull/5210 breaks some of the gnat2goto regression tests.  If @xbauch has a moment, an opinion on how to fix it would be most appreciated.

**Comment by chrisr-diffblue** [comment]
@martin-cs Petr left Diffblue at the end of Feb I think, so I'm not sure if he is likely to have time/interest in working on CBMC/gnat2goto anymore.

**Comment by martin-cs** [comment]
@chrisr-diffblue : thanks.  I was going to @ the reviewers of the https://github.com/diffblue/cbmc/pull/5210 but then I noticed I reviewed that so I really should be able to figure it out.
Would it be possible to add @tjj2017 as an approved reviewer?

@xbauch : apologies.

**Comment by chrisr-diffblue** [comment]
@martin-cs I'll look into getting Trevor added as an approved reviewer. I'm not 100% sure I have full authority to do so, but I'll check.

**Comment by chrisr-diffblue** [comment]
@martin-cs @tjj2017 I don't have appropriate permissions to add Trevor as a collaborator, but Peter Schrammel should have just sent Trevor an invite - as soon as Trevor accepts the invite he should be an approved reviewer.

**Comment by martin-cs** [comment]
Thanks for the prompt and positive response.

**Pull request merged**
