### PR TITLE
Ignore Warnings pragma and print name of unknown pragmas

### PR DESCRIPTION
**Pull request by hannes-steffenhagen-diffblue**

### CODE REVIEW

**Comment by martin-cs** [comment]
`Process_Pragma_Declaration` as opposed to `Do_Pragma`.

**Comment by martin-cs** [comment]
Also see the original ticket for an update on this task.

**Comment by hannes-steffenhagen-diffblue** [comment]
FWIW these seem to be all SPARK pragmas. I’m not sure if we should ignore those, I imagine some of them could be useful?

**Comment by martin-cs** [comment]
@hannes-steffenhagen-diffblue : yes, I would like to support as many of them as we can but at the moment some are outside of the kind of analysis that we do.  Note for this issue we just need the "have found unknown pragma" messages improved with what they are, we aren't necessarily handling / ignoring them.

**Comment by hannes-steffenhagen-diffblue** [comment]
@martin-cs this should be all of them

**Pull request merged**
