### PR TITLE
Nondet model

### PR DESCRIPTION
**Pull request by tjj2017**
Provide of specifying ASVAT models via an annotation.

Current models are Nondet_Function and In_Type_Function.
See header of ASVAT.Modelling (asvat-modelling.ads).

### CODE REVIEW

**Comment by martin-cs** [comment]
A build failure which is probably due to the attempt I made at resolving the merge.  A rebase will probably fix this.

**Comment by martin-cs** [comment]
@chrisr-diffblue CI seems to have jammed, please can you kick it?

**Comment by chrisr-diffblue** [comment]
@martin-cs I tried applying the appropriate Size 9 steel toecap, but it looks like the build will (a) need a rebase + force push, and (b) there's an actual compile failure: https://travis-ci.org/github/diffblue/gnat2goto/builds/693545193

**Comment by martin-cs** [comment]
Thanks for the percussive maintenance.  @tjj2017 has rebased and forced push it still appears jammed.  Any chance of @chrisr-diffblue 's boot vs. CI system round 2?

**Comment by chrisr-diffblue** [comment]
I've tried kicking it again, but it still seems to fail https://travis-ci.org/github/diffblue/gnat2goto/builds/693545193 and I also note that this PR currently has conflicts. Does the rebased code still build locally for you?

**Comment by martin-cs** [comment]
@chrisr-diffblue I think everything is now working (and building and CIing and mergeable-ing) so I think we are going to declare victory at this point.

**Pull request merged**
